In [1]:
# Importing dependencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

In [2]:
training_labels = pd.read_csv('dengue_labels_train.csv')
training_features = pd.read_csv('dengue_features_train.csv')
test_features = pd.read_csv('dengue_features_test.csv')
submission = pd.read_csv('submission_format.csv')

In [3]:
# for easy cleaning
data = [training_features,test_features]

In [4]:
print(training_labels.shape)
print(training_features.shape)
print(test_features.shape)

(1456, 4)
(1456, 24)
(416, 24)

In [5]:
# making copies for later use
training_labels_copy = training_labels.copy()
training_features_copy = training_features.copy()
test_features_copy = test_features.copy()

In [6]:
training_features.head()

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
0,sj,1990,18,1990-04-30,0.122600,0.103725,0.198483,0.177617,12.42,297.572857,...,32.00,73.365714,12.42,14.012857,2.628571,25.442857,6.900000,29.4,20.0,16.0
1,sj,1990,19,1990-05-07,0.169900,0.142175,0.162357,0.155486,22.82,298.211429,...,17.94,77.368571,22.82,15.372857,2.371429,26.714286,6.371429,31.7,22.2,8.6
2,sj,1990,20,1990-05-14,0.032250,0.172967,0.157200,0.170843,34.54,298.781429,...,26.10,82.052857,34.54,16.848571,2.300000,26.714286,6.485714,32.2,22.8,41.4
3,sj,1990,21,1990-05-21,0.128633,0.245067,0.227557,0.235886,15.36,298.987143,...,13.90,80.337143,15.36,16.672857,2.428571,27.471429,6.771429,33.3,23.3,4.0
4,sj,1990,22,1990-05-28,0.196200,0.262200,0.251200,0.247340,7.52,299.518571,...,12.20,80.460000,7.52,17.210000,3.014286,28.942857,9.371429,35.0,23.9,5.8

In [7]:
training_features.columns

Index(['city', 'year', 'weekofyear', 'week_start_date', 'ndvi_ne', 'ndvi_nw',
       'ndvi_se', 'ndvi_sw', 'precipitation_amt_mm', 'reanalysis_air_temp_k',
       'reanalysis_avg_temp_k', 'reanalysis_dew_point_temp_k',
       'reanalysis_max_air_temp_k', 'reanalysis_min_air_temp_k',
       'reanalysis_precip_amt_kg_per_m2',
       'reanalysis_relative_humidity_percent', 'reanalysis_sat_precip_amt_mm',
       'reanalysis_specific_humidity_g_per_kg', 'reanalysis_tdtr_k',
       'station_avg_temp_c', 'station_diur_temp_rng_c', 'station_max_temp_c',
       'station_min_temp_c', 'station_precip_mm'],
      dtype='object')

In [8]:
training_labels.columns

Index(['city', 'year', 'weekofyear', 'total_cases'], dtype='object')

# Handling null values

In [9]:
len(training_features[training_features.isnull().any(axis=1)])

257

In [10]:
training_features[training_features.isnull().any(axis=1)]

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
5,sj,1990,23,1990-06-04,NaN,0.174850,0.254314,0.181743,9.58,299.630000,...,26.49,79.891429,9.58,17.212857,2.100000,28.114286,6.942857,34.4,23.9,39.1
9,sj,1990,27,1990-07-02,NaN,0.121550,0.160683,0.202567,14.41,300.154286,...,28.40,81.281429,14.41,18.071429,2.014286,28.328571,6.514286,33.9,24.4,1.1
13,sj,1990,31,1990-07-30,NaN,0.247150,0.379700,0.381357,32.66,299.862857,...,34.60,80.584286,32.66,17.594286,2.585714,28.242857,8.085714,34.4,22.8,37.6
14,sj,1990,32,1990-08-06,NaN,0.064333,0.164443,0.138857,28.80,300.391429,...,20.00,79.650000,28.80,17.950000,2.328571,28.200000,7.557143,33.3,23.3,11.4
15,sj,1990,33,1990-08-13,NaN,0.128033,0.206957,0.168243,90.75,299.958571,...,101.90,84.178571,90.75,18.515714,1.857143,28.042857,6.685714,32.8,22.8,44.7
24,sj,1990,42,1990-10-15,NaN,0.070200,0.181617,0.165750,143.55,299.195714,...,279.60,85.621429,143.55,18.115714,1.871429,27.628571,7.400000,32.8,23.3,61.8
36,sj,1991,2,1991-01-08,NaN,0.100467,0.251900,0.137617,15.85,297.674286,...,26.33,76.628571,15.85,14.671429,1.885714,24.914286,6.314286,28.3,21.1,31.7
37,sj,1991,3,1991-01-15,NaN,0.293567,0.259943,0.217900,0.00,297.422857,...,27.40,78.500000,0.00,14.798571,2.000000,25.242857,6.571429,29.4,21.1,16.5
42,sj,1991,8,1991-02-19,NaN,0.209400,0.108433,0.119400,0.00,297.414286,...,26.20,79.740000,0.00,15.035714,2.571429,25.842857,8.471429,32.2,20.0,17.8
45,sj,1991,11,1991-03-12,NaN,NaN,0.213250,0.240543,0.00,297.431429,...,13.37,78.138571,0.00,14.787143,2.728571,25.928571,8.971429,31.7,20.6,3.6
51,sj,1991,17,1991-04-23,NaN,0.188450,0.188314,0.224943,32.72,298.074286,...,19.70,78.447143,32.72,15.461429,2.300000,26.528571,8.014286,32.8,21.7,3.5
54,sj,1991,20,1991-05-14,NaN,0.104550,0.151150,0.096400,4.16,298.325714,...,35.37,80.067143,4.16,15.974286,2.500000,26.528571,6.585714,30.6,22.8,32.8
61,sj,1991,27,1991-07-02,NaN,0.177933,0.201529,0.198157,26.70,299.371429,...,51.99,81.694286,26.70,17.352857,2.142857,28.371429,6.600000,32.8,23.9,24.7
62,sj,1991,28,1991-07-09,0.096900,NaN,0.138050,0.167917,6.13,300.001429,...,18.70,77.877143,6.13,17.151429,2.428571,28.414286,6.671429,32.8,24.4,4.6
63,sj,1991,29,1991-07-16,NaN,0.077333,0.099829,0.116643,29.67,300.234286,...,23.60,78.241429,29.67,17.472857,2.428571,28.800000,6.914286,33.9,23.9,12.2
65,sj,1991,31,1991-07-30,NaN,NaN,0.190643,0.159329,48.41,299.852857,...,34.39,81.897143,48.41,17.878571,2.300000,28.571429,6.342857,33.3,25.0,18.0
67,sj,1991,33,1991-08-13,0.059300,NaN,0.155100,0.156700,0.00,300.420000,...,20.40,79.197143,0.00,17.911429,2.185714,29.428571,5.471429,33.3,25.6,3.3
85,sj,1991,51,1991-12-17,NaN,0.046133,0.114400,0.040457,0.00,298.084286,...,8.76,72.861429,0.00,14.335714,2.071429,25.000000,6.157143,28.9,20.6,6.1
87,sj,1992,1,1992-01-01,0.125100,0.157867,0.185283,0.181367,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,sj,1992,5,1992-01-29,NaN,0.048300,0.173671,0.191929,0.00,297.420000,...,6.50,75.220000,0.00,14.185714,2.442857,24.800000,6.585714,28.9,20.0,9.2
93,sj,1992,7,1992-02-12,NaN,0.130500,0.195743,0.178857,NaN,297.798571,...,20.10,82.875714,NaN,16.060000,2.200000,26.028571,6.571429,32.2,20.0,1.3
94,sj,1992,8,1992-02-19,NaN,0.184467,0.194614,0.203057,NaN,297.898571,...,4.40,77.295714,NaN,15.012857,2.585714,25.757143,7.385714,33.9,21.7,8.9
95,sj,1992,9,1992-02-26,0.107050,0.081500,0.165243,0.163057,NaN,297.472857,...,14.40,76.037143,NaN,14.381429,2.414286,25.285714,6.171429,29.4,21.7,16.0
96,sj,1992,10,1992-03-04,NaN,0.182180,0.191086,0.192857,0.00,297.651429,...,5.50,76.878571,0.00,14.701429,2.314286,25.657143,7.814286,31.1,20.6,2.9
99,sj,1992,13,1992-03-25,NaN,NaN,0.134843,0.106800,0.00,297.218571,...,21.00,80.238571,0.00,14.968571,2.800000,26.200000,5.714286,32.2,22.2,2.3
108,sj,1992,22,1992-05-27,0.121500,NaN,0.219157,0.213014,186.25,298.615714,...,130.30,87.301429,186.25,17.832857,2.357143,27.428571,5.957143,31.7,23.9,80.2
114,sj,1992,28,1992-07-08,NaN,0.192000,0.146857,0.153071,1.86,300.285714,...,5.40,78.497143,1.86,17.568571,2.785714,28.728571,6.614286,32.8,24.4,1.8
122,sj,1992,36,1992-09-02,NaN,0.217500,0.124014,0.125657,61.55,300.108571,...,34.36,79.204286,61.55,17.564286,2.200000,28.728571,7.485714,34.4,24.4,6.5
137,sj,1992,51,1992-12-16,NaN,0.066425,0.192343,0.194129,0.00,298.285714,...,24.94,76.661429,0.00,15.251429,2.642857,26.685714,8.385714,32.2,21.7,47.5
139,sj,1993,53,1993-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1170,iq,2005,53,2005-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1190,iq,2005,20,2005-05-21,0.270086,0.173757,0.210457,0.229743,56.22,297.532857,...,49.10,93.918571,56.22,17.957143,7.542857,NaN,NaN,33.2,23.6,95.9
1192,iq,2005,22,2005-06-04,0.378286,0.369371,0.363186,0.361243,61.75,298.434286,...,34.92,86.701429,61.75,17.200000,10.014286,NaN,NaN,33.9,20.9,78.9
1203,iq,2005,33,2005-08-20,0.266986,0.293929,0.336000,0.292486,17.85,299.605714,...,6.00,64.658571,17.85,13.590000,14.200000,NaN,NaN,32.8,17.3,69.6
1206,iq,2005,36,2005-09-10,0.335429,0.200714,0.322886,0.309143,36.98,300.058571,...,4.20,71.971429,36.98,15.518571,13.714286,NaN,NaN,NaN,21.8,44.0
1207,iq,2005,37,2005-09-17,0.239429,0.214871,0.239043,0.227600,18.66,298.880000,...,35.30,83.730000,18.66,17.222857,9.928571,NaN,NaN,NaN,NaN,1.3
1209,iq,2005,39,2005-10-01,0.405417,0.428771,0.370600,0.421086,29.80,301.175714,...,4.20,67.212857,29.80,15.331429,14.828571,28.650000,13.500000,37.1,20.7,NaN
1215,iq,2005,45,2005-11-12,0.393800,0.298629,0.401986,0.410371,75.36,298.600000,...,143.80,89.310000,75.36,17.974286,9.700000,NaN,NaN,34.6,22.3,8.9
1223,iq,2006,1,2006-01-08,0.199514,0.239343,0.227657,0.215500,38.78,298.832857,...,15.20,73.161429,38.78,14.524286,12.314286,NaN,NaN,34.5,19.7,70.1
1225,iq,2006,3,2006-01-22,0.174300,0.133643,0.111757,0.194429,88.85,298.460000,...,52.20,89.955714,88.85,17.941429,9.142857,NaN,NaN,33.8,21.5,54.8
1227,iq,2006,5,2006-02-05,0.379114,0.305329,0.345971,0.371571,34.17,297.165714,...,63.98,97.320000,34.17,18.264286,5.528571,NaN,NaN,33.7,21.5,118.9
1272,iq,2006,50,2006-12-17,0.378500,0.302033,0.349229,0.414786,157.75,298.158571,...,63.00,95.875714,157.75,19.111429,6.400000,NaN,NaN,33.8,NaN,NaN
1273,iq,2006,51,2006-12-24,0.327820,0.261920,0.381467,0.352950,111.48,297.680000,...,80.20,95.078571,111.48,18.358571,6.542857,NaN,NaN,32.9,23.5,NaN
1300,iq,2007,27,2007-07-02,0.181443,0.269229,0.193457,0.209943,1.59,296.828571,...,1.40,78.074286,1.59,13.804286,12.228571,25.900000,10.566667,32.0,19.6,NaN
1326,iq,2008,1,2008-01-01,0.191471,0.155414,0.176014,0.187243,19.95,299.277143,...,21.40,78.670000,19.95,16.260000,10.728571,28.275000,11.575000,36.0,21.5,NaN
1329,iq,2008,4,2008-01-22,0.277971,0.324929,0.221914,0.295671,102.59,297.207143,...,93.43,95.125714,102.59,17.840000,5.971429,NaN,NaN,31.3,21.9,46.3
1337,iq,2008,12,2008-03-18,0.238333,0.232729,0.123943,0.200071,91.87,296.755714,...,90.50,93.451429,91.87,16.997143,7.214286,NaN,NaN,31.7,22.0,100.9
1349,iq,2008,24,2008-06-10,0.293743,0.264367,0.246629,0.291957,13.27,296.187143,...,12.90,88.810000,13.27,15.375714,9.300000,NaN,NaN,NaN,17.8,6.4
1350,iq,2008,25,2008-06-17,0.224029,0.175471,0.265657,0.245214,111.18,296.742857,...,57.87,95.860000,111.18,17.447143,6.957143,NaN,NaN,NaN,21.0,79.8
1351,iq,2008,26,2008-06-24,0.197043,0.277983,0.213943,0.265614,89.88,296.458571,...,61.80,93.795714,89.88,16.712857,7.385714,NaN,NaN,NaN,18.0,93.5
1352,iq,2008,27,2008-07-01,0.304829,0.233671,0.248914,0.255814,0.00,296.542857,...,9.40,86.524286,0.00,15.285714,9.442857,NaN,NaN,NaN,20.8,1.3
1353,iq,2008,28,2008-07-08,0.153850,0.149586,0.329443,0.132886,0.00,296.545714,...,7.47,85.655714,0.00,15.080000,9.271429,NaN,NaN,NaN,21.0,0.0
1354,iq,2008,29,2008-07-15,0.232386,0.213957,0.220300,0.198429,62.84,296.078571,...,27.33,93.055714,62.84,16.142857,8.442857,NaN,NaN,NaN,21.0,44.2
1365,iq,2008,40,2008-09-30,0.393086,0.378271,0.343700,0.404843,24.28,299.178571,...,121.30,79.502857,24.28,16.331429,12.785714,NaN,NaN,36.0,19.6,1.0
1378,iq,2009,1,2009-01-01,0.151286,0.161686,0.153271,0.119443,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1400,iq,2009,23,2009-06-04,0.114000,0.092443,0.097471,0.126286,42.22,296.125714,...,53.91,95.507143,42.22,16.757143,6.071429,28.100000,11.800000,34.0,22.2,NaN
1409,iq,2009,32,2009-08-06,0.395000,0.352733,0.484286,0.401914,9.79,297.370000,...,34.40,87.811429,9.79,16.337143,11.757143,27.975000,12.100000,35.4,20.5,NaN
1430,iq,2010,53,2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1431,iq,2010,1,2010-01-08,0.124571,0.179129,0.163843,0.135471,27.04,299.264286,...,8.50,78.271429,27.04,16.127143,11.100000,28.600000,12.300000,35.1,21.8,NaN
1444,iq,2010,14,2010-04-09,0.242843,0.272757,0.202271,0.260114,93.76,299.115714,...,164.70,95.182857,93.76,20.078571,7.714286,29.200000,12.300000,35.4,22.5,NaN

In [11]:
# 22 rows
# Lets do a due dilligence check with another column
training_features[training_features['ndvi_sw'].isnull()]

,city,year,weekofyear,week_start_date,ndvi_ne,ndvi_nw,ndvi_se,ndvi_sw,precipitation_amt_mm,reanalysis_air_temp_k,...,reanalysis_precip_amt_kg_per_m2,reanalysis_relative_humidity_percent,reanalysis_sat_precip_amt_mm,reanalysis_specific_humidity_g_per_kg,reanalysis_tdtr_k,station_avg_temp_c,station_diur_temp_rng_c,station_max_temp_c,station_min_temp_c,station_precip_mm
139,sj,1993,53,1993-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,sj,1994,52,1994-01-01,NaN,NaN,NaN,NaN,5.25,298.527143,...,3.40,78.018571,5.25,15.780000,2.442857,26.971429,8.200000,32.8,21.7,0.3
229,sj,1994,38,1994-09-24,NaN,NaN,NaN,NaN,39.22,299.885714,...,50.70,79.314286,39.22,17.354286,1.985714,28.371429,6.185714,32.2,24.4,34.3
230,sj,1994,39,1994-10-01,NaN,NaN,NaN,NaN,55.88,299.508571,...,45.20,80.372857,55.88,17.248571,2.600000,28.014286,6.700000,33.9,23.3,31.5
231,sj,1994,40,1994-10-08,NaN,NaN,NaN,NaN,0.63,300.377143,...,2.80,74.117143,0.63,16.744286,2.628571,28.714286,6.900000,34.4,24.4,8.2
232,sj,1994,41,1994-10-15,NaN,NaN,NaN,NaN,16.70,299.638571,...,40.80,78.225714,16.70,16.900000,2.728571,28.328571,7.657143,35.0,23.9,39.2
233,sj,1994,42,1994-10-22,NaN,NaN,NaN,NaN,75.57,300.238571,...,15.81,76.348571,75.57,17.124286,3.028571,28.571429,7.442857,35.0,23.9,5.4
234,sj,1994,43,1994-10-29,NaN,NaN,NaN,NaN,111.52,298.811429,...,64.85,85.417143,111.52,17.641429,1.657143,27.671429,7.271429,32.8,23.3,39.2
235,sj,1994,44,1994-11-05,NaN,NaN,NaN,NaN,5.41,299.867143,...,15.60,78.685714,5.41,17.264286,2.328571,28.157143,6.842857,32.2,24.4,1.9
236,sj,1994,45,1994-11-12,NaN,NaN,NaN,NaN,32.26,299.297143,...,36.60,80.095714,32.26,16.984286,2.228571,27.314286,6.928571,31.7,22.2,54.5
237,sj,1994,46,1994-11-19,NaN,NaN,NaN,NaN,32.17,299.198571,...,47.50,83.584286,32.17,17.644286,1.771429,27.285714,7.314286,32.8,22.2,47.5
238,sj,1994,47,1994-11-26,NaN,NaN,NaN,NaN,11.16,299.422857,...,23.70,83.502857,11.16,17.848571,2.400000,27.857143,7.600000,33.9,23.3,49.3
239,sj,1994,48,1994-12-03,NaN,NaN,NaN,NaN,17.52,298.851429,...,27.40,78.560000,17.52,16.178571,2.100000,26.885714,7.571429,31.7,21.1,35.9
240,sj,1994,49,1994-12-10,NaN,NaN,NaN,NaN,45.95,297.808571,...,106.09,85.570000,45.95,16.580000,1.500000,26.371429,6.185714,30.0,22.2,58.2
241,sj,1994,50,1994-12-17,NaN,NaN,NaN,NaN,0.00,298.624286,...,16.50,75.455714,0.00,15.327143,2.285714,26.585714,7.471429,31.7,21.7,7.4
242,sj,1994,51,1994-12-24,NaN,NaN,NaN,NaN,0.00,298.581429,...,12.20,76.914286,0.00,15.595714,2.728571,26.642857,8.185714,31.7,22.2,12.9
451,sj,1999,53,1999-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
611,sj,2002,5,2002-01-29,NaN,NaN,NaN,NaN,0.00,298.200000,...,10.80,76.920000,0.00,15.187143,2.185714,25.657143,5.771429,29.4,21.7,38.1
763,sj,2005,53,2005-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1018,iq,2002,5,2002-01-29,NaN,NaN,NaN,NaN,59.40,296.858571,...,43.12,96.267143,59.40,17.690000,5.228571,26.300000,9.700000,32.5,20.8,120.2
1170,iq,2005,53,2005-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1430,iq,2010,53,2010-01-01,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
# we are going to drop this rows
rows_to_drop = [139,191,229,230,231,232,233,234,235,236,237,238,239,240,241,242,451,611,763,1018,1170,1430]
training_features = training_features.drop(training_features.index[[rows_to_drop ]])

In [26]:
training_labels = training_labels.drop(training_labels.index[[rows_to_drop ]])

In [13]:
training_features.shape

(1434, 24)

In [27]:
training_labels.shape

(1434, 4)

In [14]:
1434+22

1456

In [14]:
training_features[training_features['ndvi_se'].isnull()]

Empty DataFrame
Columns: [city, year, weekofyear, week_start_date, ndvi_ne, ndvi_nw, ndvi_se, ndvi_sw, precipitation_amt_mm, reanalysis_air_temp_k, reanalysis_avg_temp_k, reanalysis_dew_point_temp_k, reanalysis_max_air_temp_k, reanalysis_min_air_temp_k, reanalysis_precip_amt_kg_per_m2, reanalysis_relative_humidity_percent, reanalysis_sat_precip_amt_mm, reanalysis_specific_humidity_g_per_kg, reanalysis_tdtr_k, station_avg_temp_c, station_diur_temp_rng_c, station_max_temp_c, station_min_temp_c, station_precip_mm]
Index: []

[0 rows x 24 columns]

In [15]:
training_features.isnull().any(axis=0)

city                                     False
year                                     False
weekofyear                               False
week_start_date                          False
ndvi_ne                                   True
ndvi_nw                                   True
ndvi_se                                  False
ndvi_sw                                  False
precipitation_amt_mm                      True
reanalysis_air_temp_k                     True
reanalysis_avg_temp_k                     True
reanalysis_dew_point_temp_k               True
reanalysis_max_air_temp_k                 True
reanalysis_min_air_temp_k                 True
reanalysis_precip_amt_kg_per_m2           True
reanalysis_relative_humidity_percent      True
reanalysis_sat_precip_amt_mm              True
reanalysis_specific_humidity_g_per_kg     True
reanalysis_tdtr_k                         True
station_avg_temp_c                        True
station_diur_temp_rng_c                   True
station_max_temp_c                        True
station_min_temp_c                        True
station_precip_mm                         True
dtype: bool

In [17]:
# fillling null values
for df in data:
    df['ndvi_ne'].fillna(training_features.ndvi_ne.median(), inplace = True)
    df['ndvi_nw'].fillna(training_features.ndvi_nw.median(), inplace = True)
    df['precipitation_amt_mm'].fillna(training_features.precipitation_amt_mm.median(), inplace = True)
    df['reanalysis_air_temp_k'].fillna(training_features.reanalysis_air_temp_k.median(), inplace = True)
    df['reanalysis_avg_temp_k'].fillna(training_features.reanalysis_avg_temp_k.median(), inplace = True)
    df['reanalysis_dew_point_temp_k'].fillna(training_features.reanalysis_dew_point_temp_k.median(), inplace = True)
    df['reanalysis_max_air_temp_k'].fillna(training_features.reanalysis_max_air_temp_k.median(), inplace = True)
    df['reanalysis_min_air_temp_k'].fillna(training_features.reanalysis_min_air_temp_k.median(), inplace = True)
    df['reanalysis_precip_amt_kg_per_m2'].fillna(training_features.reanalysis_precip_amt_kg_per_m2.median(), inplace = True)
    df['reanalysis_relative_humidity_percent'].fillna(training_features.reanalysis_relative_humidity_percent.median(), inplace = True)
    df['reanalysis_sat_precip_amt_mm'].fillna(training_features.reanalysis_sat_precip_amt_mm.median(), inplace = True)
    df['reanalysis_specific_humidity_g_per_kg'].fillna(training_features.reanalysis_specific_humidity_g_per_kg.median(), inplace = True)
    df['reanalysis_tdtr_k'].fillna(training_features.reanalysis_tdtr_k.median(), inplace = True)
    df['station_avg_temp_c'].fillna(training_features.station_avg_temp_c.median(), inplace = True)
    df['station_diur_temp_rng_c'].fillna(training_features.station_diur_temp_rng_c.median(), inplace = True)
    df['station_max_temp_c'].fillna(training_features.station_max_temp_c.median(), inplace = True)
    df['station_min_temp_c'].fillna(training_features.station_min_temp_c.median(), inplace = True)
    df['station_precip_mm'].fillna(training_features.station_precip_mm.median(), inplace = True)

In [16]:

training_features['ndvi_ne'].fillna(training_features.ndvi_ne.median(), inplace = True)
training_features['ndvi_nw'].fillna(training_features.ndvi_nw.median(), inplace = True)
training_features['precipitation_amt_mm'].fillna(training_features.precipitation_amt_mm.median(), inplace = True)
training_features['reanalysis_air_temp_k'].fillna(training_features.reanalysis_air_temp_k.median(), inplace = True)
training_features['reanalysis_avg_temp_k'].fillna(training_features.reanalysis_avg_temp_k.median(), inplace = True)
training_features['reanalysis_dew_point_temp_k'].fillna(training_features.reanalysis_dew_point_temp_k.median(), inplace = True)
training_features['reanalysis_max_air_temp_k'].fillna(training_features.reanalysis_max_air_temp_k.median(), inplace = True)
training_features['reanalysis_min_air_temp_k'].fillna(training_features.reanalysis_min_air_temp_k.median(), inplace = True)
training_features['reanalysis_precip_amt_kg_per_m2'].fillna(training_features.reanalysis_precip_amt_kg_per_m2.median(), inplace = True)
training_features['reanalysis_relative_humidity_percent'].fillna(training_features.reanalysis_relative_humidity_percent.median(), inplace = True)
training_features['reanalysis_sat_precip_amt_mm'].fillna(training_features.reanalysis_sat_precip_amt_mm.median(), inplace = True)
training_features['reanalysis_specific_humidity_g_per_kg'].fillna(training_features.reanalysis_specific_humidity_g_per_kg.median(), inplace = True)
training_features['reanalysis_tdtr_k'].fillna(training_features.reanalysis_tdtr_k.median(), inplace = True)
training_features['station_avg_temp_c'].fillna(training_features.station_avg_temp_c.median(), inplace = True)
training_features['station_diur_temp_rng_c'].fillna(training_features.station_diur_temp_rng_c.median(), inplace = True)
training_features['station_max_temp_c'].fillna(training_features.station_max_temp_c.median(), inplace = True)
training_features['station_min_temp_c'].fillna(training_features.station_min_temp_c.median(), inplace = True)
training_features['station_precip_mm'].fillna(training_features.station_precip_mm.median(), inplace = True)

In [21]:
test_features['ndvi_ne'].fillna(test_features.ndvi_ne.median(), inplace = True)
test_features['ndvi_nw'].fillna(test_features.ndvi_nw.median(), inplace = True)
test_features['precipitation_amt_mm'].fillna(test_features.precipitation_amt_mm.median(), inplace = True)
test_features['reanalysis_air_temp_k'].fillna(test_features.reanalysis_air_temp_k.median(), inplace = True)
test_features['reanalysis_avg_temp_k'].fillna(test_features.reanalysis_avg_temp_k.median(), inplace = True)
test_features['reanalysis_dew_point_temp_k'].fillna(test_features.reanalysis_dew_point_temp_k.median(), inplace = True)
test_features['reanalysis_max_air_temp_k'].fillna(test_features.reanalysis_max_air_temp_k.median(), inplace = True)
test_features['reanalysis_min_air_temp_k'].fillna(test_features.reanalysis_min_air_temp_k.median(), inplace = True)
test_features['reanalysis_precip_amt_kg_per_m2'].fillna(test_features.reanalysis_precip_amt_kg_per_m2.median(), inplace = True)
test_features['reanalysis_relative_humidity_percent'].fillna(test_features.reanalysis_relative_humidity_percent.median(), inplace = True)
test_features['reanalysis_sat_precip_amt_mm'].fillna(test_features.reanalysis_sat_precip_amt_mm.median(), inplace = True)
test_features['reanalysis_specific_humidity_g_per_kg'].fillna(test_features.reanalysis_specific_humidity_g_per_kg.median(), inplace = True)
test_features['reanalysis_tdtr_k'].fillna(test_features.reanalysis_tdtr_k.median(), inplace = True)
test_features['station_avg_temp_c'].fillna(test_features.station_avg_temp_c.median(), inplace = True)
test_features['station_diur_temp_rng_c'].fillna(test_features.station_diur_temp_rng_c.median(), inplace = True)
test_features['station_max_temp_c'].fillna(test_features.station_max_temp_c.median(), inplace = True)
test_features['station_min_temp_c'].fillna(test_features.station_min_temp_c.median(), inplace = True)
test_features['station_precip_mm'].fillna(test_features.station_precip_mm.median(), inplace = True)

In [24]:
training_features.isnull().any(axis=0)

city                                     False
year                                     False
weekofyear                               False
week_start_date                          False
ndvi_ne                                  False
ndvi_nw                                  False
ndvi_se                                  False
ndvi_sw                                  False
precipitation_amt_mm                     False
reanalysis_air_temp_k                    False
reanalysis_avg_temp_k                    False
reanalysis_dew_point_temp_k              False
reanalysis_max_air_temp_k                False
reanalysis_min_air_temp_k                False
reanalysis_precip_amt_kg_per_m2          False
reanalysis_relative_humidity_percent     False
reanalysis_sat_precip_amt_mm             False
reanalysis_specific_humidity_g_per_kg    False
reanalysis_tdtr_k                        False
station_avg_temp_c                       False
station_diur_temp_rng_c                  False
station_max_temp_c                       False
station_min_temp_c                       False
station_precip_mm                        False
dtype: bool

In [28]:
test_features.shape

(416, 24)

In [29]:
1456+416

1872

In [34]:
1500/1872

0.8012820512820513

In [35]:
# Saving clean data to csv
training_features.to_csv('train_features_clean.csv',index = False)
training_labels.to_csv('train_labels_clean.csv',index = False)
test_features.to_csv('test_features_clean.csv',index = False)